# Generated by Django 4.2.7 on 2026-01-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spreadsheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('histogram', 'Histogram'), ('scatter', 'Scatter Plot')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('x_axis_column', models.IntegerField()),
                ('y_axis_columns', models.JSONField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='spreadsheets.spreadsheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['spreadsheet', '-updated_at'], name='charts_spreads_f632fa_idx'), models.Index(fields=['user', '-updated_at'], name='charts_user_id_530a9b_idx')],
            },
        ),
    ]
