# Generated by Django 4.2.7 on 2026-01-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=100)),
                ('column_count', models.IntegerField(default=26)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spreadsheets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('column_index', models.IntegerField()),
                ('value', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('formula', 'Formula')], default='text', max_length=20)),
                ('style', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheets.spreadsheet')),
            ],
            options={
                'db_table': 'cells',
            },
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['user', '-updated_at'], name='spreadsheet_user_id_8990a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['spreadsheet', 'row_index', 'column_index'], name='cells_spreads_d376f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('spreadsheet', 'row_index', 'column_index')},
        ),
    ]
