# Generated by Django 4.2.7 on 2026-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='worksheet_count',
            field=models.IntegerField(default=1),
        ),
    ]
