# Generated by Django 4.2.7 on 2026-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0002_spreadsheet_worksheet_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='worksheet_count',
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='worksheet_names',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
