# Generated by Django 4.2.7 on 2026-01-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0005_create_worksheets_for_existing_spreadsheets'),
    ]

    operations = [
        # Constraints already defined in models, migration is a no-op
    ]
