# Generated by Django 4.2.7 on 2026-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0006_remove_cell_cells_spreads_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['user', '-is_favorite', '-updated_at'], name='spreadsheet_user_id_335570_idx'),
        ),
    ]
