# Generated by Django 4.2.7 on 2026-01-02 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('summary_stats', 'Summary Statistics'), ('correlation', 'Correlation'), ('regression', 'Linear Regression'), ('custom', 'Custom Analysis')], max_length=50)),
                ('selected_columns', models.JSONField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
