# Generated by Django 4.2.7 on 2026-01-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('spreadsheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='spreadsheets.spreadsheet'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['spreadsheet', '-created_at'], name='analyses_spreads_0a3588_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', '-created_at'], name='analyses_user_id_0211ba_idx'),
        ),
    ]
